language: android
dist: trusty
android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra-google-google_play_services
before_install:
- openssl aes-256-cbc -K $encrypted_f761570c4ae9_key -iv $encrypted_f761570c4ae9_iv
  -in google-services.json.enc -out google-services.json -d