language: android
dist: trusty
android:
  components:
  - build-tools-28.0.3
  - android-26
  - extra-google-google_play_services
before_install:
- openssl aes-256-cbc -K $encrypted_fd8d34b142d0_key -iv $encrypted_fd8d34b142d0_iv
  -in google-services.json.enc -out app/google-services.json -d
env:
 global:
 - ANDROID_API=26
 - ANDROID_BUILD_TOOLS=28.0.3

script:
- ./gradlew clean test build